name: Build BakkesMod Plugin

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Download BakkesMod SDK
      run: git clone https://github.com/bakkesmodorg/BakkesModSDK.git

    - name: Download ImGui
      run: git clone --depth 1 --branch v1.88 https://github.com/ocornut/imgui.git BakkesModSDK/include/imgui

    - name: Configure CMake
      run: cmake -B build -S . -A x64

    - name: Build Plugin
      run: cmake --build build --config Release

    - name: Upload DLL Artifact
    - uses: actions/upload-artifact@v4
    with:
      name: baluPlugin
      path: build/Release/baluPlugin.dll
